
package com.engineer.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0_02
 * 
 */
@XmlRootElement(name = "HelloException", namespace = "http://www.morly.com/wstest")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HelloException", namespace = "http://www.morly.com/wstest")
public class HelloExceptionBean {

    private String message;

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
