
package com.engineer.webservice.client.ref;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Example", targetNamespace = "http://www.morly.com/wstest", wsdlLocation = "http://localhost:8080/hello?wsdl")
public class Example_Service
    extends Service
{

    private final static URL EXAMPLE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/hello?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        EXAMPLE_WSDL_LOCATION = url;
    }

    public Example_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Example_Service() {
        super(EXAMPLE_WSDL_LOCATION, new QName("http://www.morly.com/wstest", "Example"));
    }

    /**
     * 
     * @return
     *     returns Example
     */
    @WebEndpoint(name = "ExamplePort")
    public Example getExamplePort() {
        return (Example)super.getPort(new QName("http://www.morly.com/wstest", "ExamplePort"), Example.class);
    }

}
