
package com.engineer.webservice.client.ref;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "HelloException", targetNamespace = "http://www.morly.com/wstest")
public class HelloException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HelloException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public HelloException_Exception(String message, HelloException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public HelloException_Exception(String message, HelloException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.engineer.webservice.client.ref.HelloException
     */
    public HelloException getFaultInfo() {
        return faultInfo;
    }

}
